import Login from './Login/';
import Splash from './Splash/';
import Register from './Register/';
import Home from './Menu/Home/';
import Chat from './Menu/Chat/';
import Timeline from './Menu/Timeline/';
import Profile from './Menu/Profile/';
import ChatWindow from './ChatWindow/';
import FindFriend from './FindFriend/';
import Invitation from './Invitation/';
import EditProfile from './EditProfile/';
import FriendsProfile from './FriendsProfile/';
import PostReply from './PostReply';
import NewGroup from './NewGroup';
import CreatePost from './CreatePost';

export {ChatWindow};
export {Home};
export {Chat};
export {Timeline};
export {Profile};
export {Register};
export {Login};
export {Splash};
export {FindFriend};
export {Invitation};
export {EditProfile};
export {FriendsProfile};
export {PostReply};
export {NewGroup};
export {CreatePost}